//! Built-in model library. `catalog.toml` is generated by `scripts/catalog/build.py`, which
//! verifies every entry against the Hugging Face Hub (pinned commit, exact files and sizes,
//! architecture and shape read from the model files themselves).

use crate::manifest::{ModelEntry, ModelShape};
use llmario_core::ModelFormat;
use serde::Deserialize;

const BUILTIN: &str = include_str!("../catalog.toml");

#[derive(Deserialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CatalogEntry {
    pub id: String,
    pub family: String,
    /// Display name, e.g. "Qwen3.8 27B".
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub publisher: Option<String>,
    /// Release month, `YYYY-MM`.
    #[serde(default)]
    pub released: Option<String>,
    /// Parameter count as published, e.g. "35B (3B active)".
    #[serde(default)]
    pub params: Option<String>,
    /// What the model is good at: chat, reasoning, coding, agents, multilingual, long-context, small.
    #[serde(default)]
    pub tasks: Vec<String>,
    pub format: ModelFormat,
    pub repo: String,
    /// Git ref resolved at pull time; the generated catalog pins a commit SHA.
    pub revision: String,
    /// Exact files to fetch. Empty = every allowed file in the repo (MLX directories).
    #[serde(default)]
    pub files: Vec<String>,
    pub license: String,
    /// Whether the Hub repo requires accepting terms (needs HF_TOKEN).
    #[serde(default)]
    pub gated: bool,
    /// Engine-specific architecture name (GGUF `general.architecture` / MLX `model_type`).
    #[serde(default)]
    pub architecture: Option<String>,
    #[serde(default)]
    pub quantization: Option<String>,
    #[serde(default)]
    pub context_max: Option<u32>,
    pub description: String,
    #[serde(default)]
    pub notes: Option<String>,
    /// Download size in bytes, for display and pre-download fit checks.
    #[serde(default)]
    pub approx_bytes: Option<u64>,
    /// Attention shape for KV-cache estimates before download.
    #[serde(default)]
    pub shape: Option<ModelShape>,
}

impl CatalogEntry {
    pub fn display_name(&self) -> &str {
        self.name.as_deref().unwrap_or(&self.id)
    }

    /// A stand-in registry entry so the memory planner can size the model before download.
    pub fn planning_entry(&self) -> ModelEntry {
        ModelEntry {
            id: self.id.clone(),
            family: Some(self.family.clone()),
            format: self.format,
            path: Default::default(),
            managed: true,
            source: None,
            license: Some(self.license.clone()),
            architecture: self.architecture.clone(),
            quantization: self.quantization.clone(),
            shape: self.shape.clone(),
            chat_template: true,
            files: vec![],
            size_bytes: self.approx_bytes.unwrap_or(0),
            added_at: String::new(),
        }
    }
}

#[derive(Deserialize, Debug)]
pub struct Catalog {
    pub models: Vec<CatalogEntry>,
}

impl Catalog {
    pub fn builtin() -> Self {
        toml::from_str(BUILTIN).expect("built-in catalog.toml is valid")
    }

    pub fn get(&self, id: &str) -> Option<&CatalogEntry> {
        self.models.iter().find(|m| m.id == id)
    }

    pub fn family(&self, family: &str) -> Vec<&CatalogEntry> {
        self.models.iter().filter(|m| m.family == family).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TASKS: &[&str] = &[
        "chat",
        "reasoning",
        "coding",
        "agents",
        "multilingual",
        "long-context",
        "small",
    ];

    #[test]
    fn builtin_catalog_is_consistent() {
        let c = Catalog::builtin();
        assert!(
            c.models.len() >= 40,
            "library has {} entries",
            c.models.len()
        );
        let mut ids: Vec<_> = c.models.iter().map(|m| &m.id).collect();
        ids.sort();
        ids.dedup();
        assert_eq!(ids.len(), c.models.len(), "catalog ids are unique");
        for m in &c.models {
            assert!(m.repo.contains('/'), "{}: repo must be org/name", m.id);
            assert!(
                m.revision.len() == 40 && m.revision.chars().all(|c| c.is_ascii_hexdigit()),
                "{}: revision must be a pinned commit",
                m.id
            );
            assert!(m.approx_bytes.unwrap_or(0) > 0, "{}: size known", m.id);
            assert!(
                m.name.is_some() && m.publisher.is_some(),
                "{}: display fields",
                m.id
            );
            assert!(m.architecture.is_some(), "{}: architecture known", m.id);
            assert!(!m.tasks.is_empty(), "{}: tasks", m.id);
            for t in &m.tasks {
                assert!(TASKS.contains(&t.as_str()), "{}: unknown task {t}", m.id);
            }
            if m.format == ModelFormat::Gguf {
                assert!(
                    !m.files.is_empty(),
                    "{}: GGUF entries must pin a file",
                    m.id
                );
            }
            for f in &m.files {
                crate::validate_relative_name(f).unwrap();
            }
        }
        // Ids that existing installs rely on stay stable.
        for id in [
            "qwen3-1.7b-mlx-4bit",
            "qwen3-1.7b-gguf-q4km",
            "qwen3-8b-mlx-4bit",
            "qwen3-8b-gguf-q4km",
            "llama3.2-3b-mlx-4bit",
            "llama3.2-3b-gguf-q4km",
        ] {
            assert!(c.get(id).is_some(), "{id} missing");
        }
        assert_eq!(c.family("qwen3-1.7b").len(), 2);
    }

    #[test]
    fn planning_entry_carries_size_and_shape() {
        let c = Catalog::builtin();
        let e = c.get("qwen3-8b-gguf-q4km").unwrap().planning_entry();
        assert!(e.weight_bytes() > 4_000_000_000);
        assert_eq!(e.shape.unwrap().n_layers, 36);
    }
}
